"""Every word it says, in German."""
from ..words.lookup import speaks

DE = {
    "start": "Start", "end": "Ende", "ret": "Rückgabe",
    "yes": "Wahr", "no": "Falsch", "again": "nochmal?",
    "key_oval": "Start / Ende", "key_rect": "Verarbeitung",
    "key_io": "Eingabe / Ausgabe", "key_diamond": "Entscheidung",
    "key_hex": "Schleife", "key_sub": "Modul aufrufen",
    "palette": "Palette", "shapes": "Formen",
    "selected": "Ausgewählte Form", "rest": "Linien und Papier",
    "fill": "Füllung", "outline": "Umriss", "text": "Text",
    "paper": "Papier", "grid": "Raster", "show_grid": "Raster anzeigen",
    "lines": "Linien und Pfeile", "reset": "Alle Farben zurücksetzen",
    "download": "Herunterladen", "dl_size": "Größe",
    "files": "Dateien", "import_head": "Importieren",
    "dl_svg": "SVG herunterladen", "dl_png": "PNG herunterladen",
    "print_it": "Diagramm drucken",
    "print_head": "Drucken",
    "print_go": "Drucken…",
    "print_paper": "Papier",
    "print_wide": "Quer",
    "print_fit": "Auf eine Seite bringen",
    "print_note": "Gedruckt wird schlicht: keine Farben, nur Linien und Wörter. Welcher Drucker und wie viele Kopien, fragt dein Browser selbst — eine Seite darf das nicht fragen.",
    "panel": "Bereich", "panel_tip": "Bereich ein- oder ausblenden",
    "png_tip": "Wie groß das PNG wird",
    "fit": "Einpassen", "actual": "Original", "zoom_in": "Vergrößern",
    "slide_left": "Links", "slide_right": "Rechts", "slide_up": "Hoch", "slide_down": "Runter",
    "hold_locked": "Fixiert", "hold_loose": "Frei",
    "lock_tip": "Das Diagramm bleibt an seinem Platz und wird in der Fläche gescrollt",
    "loose_tip": "Das Diagramm frei verschieben; eine Ecke bleibt immer sichtbar",
    "zoom_out": "Verkleinern", "pixels": "Pixel",
    "dl_scale": "Mal so groß wie gezeichnet",
    "dl_frame": "In ein Bild eingepasst",
    "png_over": "mehr, als dieser Browser zeichnen kann",
    "click_shape": "Klicke auf eine Form im Diagramm, um nur diese zu färben.",
    "palette_hint": "Eine Palette setzt alle Formen auf einmal. Was du "
                    "danach von Hand änderst, bleibt erhalten.",
    "shapes_hint": "Füllung und Umriss, für alle Formen dieser Art.",
    "apply_all": "Auf alle {n} anwenden: {what}", "clear": "Löschen",
    "rendering": "Wird erzeugt…",
    "png_big": "Der Browser konnte kein so großes PNG erzeugen. Nimm eine "
               "kleinere Größe oder speichere das SVG.",
    "png_fail": "Der Browser konnte das PNG nicht zeichnen. Der "
                "SVG-Download funktioniert weiterhin.",
    "png_capped": "{want}× ist mehr, als ein Browser-Canvas fasst; "
                  "das PNG wird mit {got}× gespeichert "
                  "({w} × {h} Pixel).",
    "flowchart": "Flussdiagramm",
    "r_head": "Ausführen",
    "r_run": "Starten",
    "r_stop": "Anhalten",
    "r_code": "Als Code",
    "r_pseudo": "Pseudocode",
    "r_slowly": "Schritt für Schritt",
    "r_follow": "Mitlaufen",
    "r_follow_tip": "Während der Schritte fährt das Diagramm zur laufenden Form und zoomt heran; der Pseudocode springt zu ihrer Zeile",
    "r_enter": "Eingeben",
    "r_hint": "Führt das Programm aus, aus dem das Diagramm entstanden ist: es fragt, wonach es fragt, gibt aus, was es ausgibt, und hebt die Form hervor, bei der es gerade ist. Wähle eine Sprache, um dasselbe Programm darin zu sehen.",
    "r_started": "Läuft...",
    "r_done": "Fertig.",
    "r_nothing": "Es gibt noch nichts auszuführen.",
    "r_steps": "{n} Schritte, {ms} ms.",
    "r_forever": "Das läuft viel zu lange ohne anzuhalten -- irgendwo ist eine Schleife, aus der es nie herauskommt.",
    "r_zero": "Das teilt durch null.",
    "r_unknown": "In {name} steht noch nichts.",
    "r_odd_op": "Mit {op} weiß ich nichts anzufangen.",
    "r_half": "Das liest sich nicht als Ganzes: {bit}",
    "r_back": "Zurück zum Lauf", "back": "Zurück",
    "r_by_hand": "Drücke Entwurf prüfen; besteht er, kann er hier laufen.",
    "h_runnable": "Das liest sich wie ein Programm. Du kannst es ausführen.",
    "h_no_start": "Es gibt keine Form, mit der begonnen wird.",
    "h_tangled": "Die Schleifen in diesem Entwurf kreuzen sich, er lässt sich daher nicht als Programm schreiben.",
    "h_not_a_program": "Die Wörter in diesen Formen lesen sich nicht wie ein Programm.",
    "r_build_first": "Erstelle ein Diagramm aus Pseudocode, dann "
                     "kann es hier ausgeführt werden.",
    "r_copy": "Kopieren",
    "r_copied": "Kopiert",
    "r_copy_no": "Bitte von Hand kopieren",
    "r_save_code": "Speichern",
    "r_pseudo_only": "Wähle Python, Java, C# oder JavaScript, um den Code zu sehen.",
    # ---- wo ein Lauf schiefging, und was das Lesen übergehen musste
    "r_at": "Zeile {line}",
    "r_show_line": "Zeig mir die Zeile, aus der das kommt",
    "r_in_mod": "in {name}, aufgerufen aus Zeile {line}",
    "r_in_mod_only": "in {name}",
    "r_mean": "Meintest du {name}?",
    "r_unknown_fn": "Es gibt kein Modul und keine Funktion namens {name}.",
    "r_odd_here": "Mit {bit} habe ich hier nicht gerechnet.",
    "r_empty_expr": "Hier steht nichts, woraus sich das ergeben könnte.",
    "r_left_over": "Am Ende bleibt {bit} übrig, ohne etwas, woran es gehört.",
    "r_open_quote": "Dieser Text wird nie geschlossen -- ein Anführungszeichen fehlt.",
    "r_open_bracket": "Diese Klammer wird geöffnet und nie geschlossen.",
    "r_shut_bracket": "Diese Klammer schließt eine, die nie geöffnet wurde.",
    "r_no_idea": "Aus dieser Zeile werde ich nicht schlau, der Lauf ist darüber hinweggegangen.",
    "r_stepped_over": "Einige Zeilen wurden übergangen, das Ausgegebene ist also vielleicht nicht alles.",
    "r_too_deep": "{name} hat sich viel zu oft selbst aufgerufen -- irgendwo hört es nicht mehr auf.",
    "r_args": "{name} verlangt {want} und hat {got} bekommen.",
    "r_no_main": "Hier gibt es keinen Hauptablauf, der Lauf hat also in {name} begonnen.",
    "w_head": "Einen Blick wert",
    "w_found": "{n} zum Anschauen im Pseudocode:",
    "w_open_if": "Zeile {line}: Dieses If wird nie geschlossen, alles darunter steht also darin. Setz ein End If dorthin, wo es aufhören soll.",
    "w_open_loop": "Zeile {line}: Diese Schleife wird nie geschlossen, alles darunter dreht sich mit. Setz ein End While dorthin, wo sie aufhören soll.",
    "w_open_for": "Zeile {line}: dieses For wird nie geschlossen, also dreht sich alles darunter mit. Setz ein End For dorthin, wo es aufhören soll.",
    "w_open_select": "Zeile {line}: Dieses Select wird nie geschlossen. Setz ein End Select dorthin, wo es aufhören soll.",
    "w_no_if": "Zeile {line}: End If, aber es ist kein If offen, das es schließen könnte.",
    "w_no_loop": "Zeile {line}: Das schließt eine Schleife, aber es ist keine offen.",
    "w_no_select": "Zeile {line}: End Select, aber es ist kein Select offen, das es schließen könnte.",
    "w_do_no_test": "Zeile {line}: Dieses Do bekommt nie eine Bedingung, es liefe also ewig. Schließ es mit Until ... oder Loop While ...",
    "w_until_alone": "Zeile {line}: Until, aber darüber steht kein Do und kein Repeat, das es beenden könnte.",
    "w_mend_change": "{word} in {instead} ändern",
    "w_mend_drop": "Zeile {line} entfernen",
    "w_mend_insert": "{text} in Zeile {line} einsetzen",
    "w_mend_tip": "Doppelklick, um das zu beheben",
    "n_rect": "Rechteck",
    "an_arrow": "Pfeil",
    "word_on_it": "Wort daran",
    "thickness": "Dicke",
    "color_of_it": "Farbe",
    "dashed": "Gestrichelt",
    "with_head": "Spitze",
    "turn_it_round": "Umdrehen",
    "m_type": "Hineinschreiben",
    "m_copy": "Noch eins",
    "c_fill": "Füllfarbe", "c_line": "Randfarbe", "c_words": "Textfarbe",
    "c_clear": "Keine eigene Farbe",
    "m_turn": "90° drehen",
    "m_solid": "Durchgezogen",
    "m_no_word": "Kein Wort",
    "m_fit": "Auf den Bildschirm passen",
    "f_save": "In eine Datei speichern",
    "f_open": "Dokument öffnen",
    "f_not_ours": "Das ist eine JSON-Datei, aber kein hier gespeicherter Entwurf.",
    "f_opened": "{name} geöffnet.",
    "f_empty": "Darin steht nichts.",
    "n_roundrect": "Abgerundeter Kasten",
    "n_offpage": "Andere Seite", "n_loop": "Schleifengrenze", "n_parallel": "Nebeneinander",
    "n_text": "Text", "n_actor": "Person", "n_callout": "Sprechblase",
    "n_cube": "Würfel", "n_step": "Schritt", "n_table": "Tabelle",
    "n_stored": "Intern gespeichert", "n_cloud": "Cloud",
    "n_card": "Karte",
    "n_note": "Notiz",
    "n_docs": "Seiten",
    "n_manual": "Handeingabe",
    "n_screen": "Bildschirm",
    "n_arrow": "Pfeil",
    "n_io_back": "Parallelogramm andersherum",
    "n_oval": "Oval",
    "n_io": "Parallelogramm",
    "n_diamond": "Raute",
    "n_hex": "Sechseck",
    "n_sub": "Kasten mit Balken",
    "n_trap": "Trapez",
    "n_doc": "Dokument",
    "n_store": "Trommel",
    "n_delay": "Warten",
    "n_circle": "Kreis",
    "shapes_for": "Form je Art",
    "shapes_for_hint": "Welche Form für welche Art von Schritt gezeichnet wird. Was der Schritt bedeutet, ändert sich nicht.",
    "size": "Größe",
    "width": "Breite",
    "height": "Höhe",
    "turn": "Drehen",
    "fit_words": "An den Text anpassen",
    "colors_here": "Farben",
    "odd_shape": "{pair} lässt sich nicht zeichnen -- siehe --help.",
    "mode_code": "Aus Pseudocode",
    "mode_hand": "Von Hand",
    "add_shape": "Form hinzufügen",
    "hand_hint": "Formen verschieben. Eine anklicken, dann Verbinden, dann die Form anklicken, zu der es weitergeht.",
    "words_in": "Text in der Form",
    "connect": "Verbinden",
    "connect_now": "Jetzt die Form anklicken, zu der es geht.",
    "goes_to": "Geht zu",
    "nothing_yet": "noch nichts",
    "delete": "Löschen",
    "check": "Entwurf prüfen",
    "checked_good": "Der Entwurf trägt: ein Start, alle Formen erreichbar, und jeder Weg endet an einem Ende.",
    "problems": "{n} zum Ansehen",
    "pick_shape": "Klicke eine Form an, um sie zu beschriften, zu verschieben oder zu verbinden.",
    "as_chart": "Diagramm",
    "untitled": "Ohne Titel",
    "p_no_start": "Nichts beginnt den Ablauf: in jede Form führt etwas hinein.",
    "p_many_starts": "In {n} Formen führt nichts hinein. Ein Diagramm beginnt an einer Stelle.",
    "p_start_kind": "Die Form, mit der alles anfängt, sollte ein Oval sein.",
    "p_no_end": "Es gibt kein Ende: kein Oval, an dem der Ablauf aufhört.",
    "p_unreached": "Zu dieser Form führt nichts.",
    "p_dead_end": "Aus dieser Form führt nichts heraus, und sie ist kein Ende.",
    "p_decision_out": "Eine Entscheidung braucht zwei Ausgänge, einen je Antwort. Diese hat {n}.",
    "p_one_out": "Diese Form hat {n} Ausgänge. Nur eine Entscheidung darf mehr als einen haben.",
    "p_same_labels": "Beide Ausgänge dieser Entscheidung sagen dasselbe.",
    "p_no_label": "Ein Ausgang einer Entscheidung braucht ein Wort.",
    "p_trapped": "Kommt der Ablauf hierher, erreicht er nie ein Ende.",
    "p_empty": "In dieser Form steht nichts.",
    "p_overlap": "Diese Form liegt auf einer anderen.",
    "p_alone": "Diese Form ist mit nichts verbunden.",
    "p_line_through": "Eine Linie läuft mitten durch diese Form. Verschiebe eine von beiden etwas.",
    "side_chart": "Diagramm", "side_colors": "Farben", "hide_panel": "Bereich ausblenden", "show_panel": "Bereich einblenden",
    "theme": "Hell oder dunkel", "theme_auto": "Auto", "theme_light": "Hell", "theme_dark": "Dunkel",
    "settings": "Einstellungen", "appearance": "Darstellung", "panel_side": "Seite des Panels",
    "side_left": "Links", "side_right": "Rechts", "full_screen": "Vollbild",
    "full_on": "Bildschirm füllen", "full_off": "Vollbild verlassen",
    "no_full": "Dieser Browser kennt kein Vollbild.",
    "p_ink": "Tinte", "p_classic": "Klassisch", "p_slate": "Schiefer",
    "p_meadow": "Wiese", "p_sunset": "Abendrot", "p_night": "Nacht",
    "pseudocode": "Pseudocode", "title": "Titel", "your_name": "Dein Name",
    "code_big": "Bildschirm füllen", "code_small": "Zurück zum Panel", "done": "Fertig",
    "code_esc": "Esc zum Schließen", "code_lines": "{n} Zeilen",
    "shape": "Form",
    "language": "Sprache", "key_switch": "Legende", "tint_switch": "Farbtöne",
    "build": "Diagramm zeichnen", "drawing": "Wird gezeichnet…",
    "no_code": "Es gibt noch keinen Pseudocode zum Zeichnen.",
    "failed": "Das ließ sich nicht zeichnen.",
    "not_answering": "Das Studio antwortet nicht ({err}).",
    "empty_chart": "Füge links deinen Pseudocode ein und klicke auf "
                   "Zeichnen.",
    "shape_auto": "Automatisch", "shape_square": "Quadratisch",
    "shape_wide": "Breit 16:9", "shape_page": "Seite", "shape_tall": "Hoch",
    "already": "Schon da {path}",
    "copied": "{n} Dateien nach {dir} kopiert",
    "wrote": "Geschrieben {path}",
    "open_this": "<- diese hier öffnen: sie zeigt das Diagramm und hat "
                 "die Download-Links",
    "style_seed": "Stil-Startwert {seed} (mit --seed {seed} kommt genau "
                  "dieses Bild wieder)",
    "nothing": "Kein Pseudocode angegeben -- nichts zu zeichnen.",
    "studio_at": "Das Flussdiagramm-Studio läuft auf {url}",
    "leave_open": "Lass dieses Fenster offen, solange du es benutzt; "
                  "Strg+C beendet es.",
    "stopped": "Studio beendet.",
    "site_done": "Dieser Ordner ist eine Website. Lade ihn zu GitHub "
                 "Pages hoch (oder zu einem anderen Datei-Host); die "
                 "Schritte stehen in {dir}/README.md.",
    "starting": "Python startet im Browser…",
    "ready": "Fertig.",
    "boot_failed": "Python konnte in diesem Browser nicht starten ({err}).",
}

speaks("de", "Deutsch", DE)
