"""Every word it says, in US English."""
from ..words.lookup import speaks

EN = {
    # ---- the words the chart draws
    "start": "Start", "end": "End", "ret": "Return",
    "yes": "True", "no": "False", "again": "again?",
    "key_oval": "Start / End", "key_rect": "Process",
    "key_io": "Input / Output", "key_diamond": "Decision",
    "key_hex": "Loop", "key_sub": "Call a module",
    # ---- the page around it
    "palette": "Palette", "shapes": "Shapes",
    "selected": "Selected shape", "rest": "Lines and paper",
    "fill": "Fill", "outline": "Outline", "text": "Words",
    "paper": "Paper", "grid": "Grid", "show_grid": "Show the grid",
    "lines": "Lines and arrows", "reset": "Put every color back",
    "download": "Download", "dl_size": "Size",
    "files": "Files", "import_head": "Import",
    "dl_svg": "Download SVG", "dl_png": "Download PNG", "panel": "Panel",
    "print_it": "Print the chart",
    "print_head": "Print",
    "print_go": "Print…",
    "print_paper": "Paper",
    "print_wide": "Sideways",
    "print_fit": "Fit on one page",
    "print_note": "It prints plain: no colors, just lines and words. Which printer, and how many copies, your browser asks for itself — a page is not allowed to ask that.",
    "panel_tip": "Show or hide the panel", "png_tip": "How big the PNG comes out",
    "fit": "Fit", "actual": "Actual", "zoom_in": "Zoom in", "zoom_out": "Zoom out",
    "slide_left": "Left", "slide_right": "Right", "slide_up": "Up", "slide_down": "Down",
    "hold_locked": "Locked", "hold_loose": "Unlocked",
    "lock_tip": "Hold the chart in place, scrolling inside the stage",
    "loose_tip": "Drag the chart anywhere; a corner of it always stays in sight",
    "pixels": "pixels",
    "dl_scale": "Times the size it is drawn",
    "dl_frame": "Fitted inside a picture",
    "png_over": "more than this browser can draw",
    "click_shape": "Click a shape in the chart to color that one on its own.",
    "palette_hint": "A palette sets every shape at once. Anything you "
                    "change by hand afterwards stays changed.",
    "shapes_hint": "Fill and outline, for every shape of that kind.",
    "apply_all": "Apply to all {n} {what}", "clear": "Clear",
    "rendering": "Rendering…",
    "png_big": "The browser could not make a PNG that big. Try a smaller "
               "size, or save the SVG.",
    "png_fail": "The browser could not draw the PNG. The SVG download "
                "still works.",
    "png_capped": "{want}× is past what a browser canvas holds, so "
                  "the PNG saves at {got}× ({w} × {h} pixels).",
    "flowchart": "Flowchart",
    "r_head": "Run it",
    "r_run": "Run",
    "r_stop": "Stop",
    "r_code": "As code",
    "r_pseudo": "Pseudocode",
    "r_slowly": "Step slowly",
    "r_follow": "Follow along",
    "r_follow_tip": "While it steps, the chart moves and zooms to the shape being done, and the pseudocode scrolls to the line it came from",
    "r_enter": "Enter",
    "r_hint": "Runs the program the chart was built from: it asks for what it asks a person for, prints what it prints, and lights up the shape it is on. Pick a language to see the same program written out in it.",
    "r_started": "Running...",
    "r_done": "Finished.",
    "r_nothing": "There is nothing to run yet.",
    "r_steps": "{n} steps, {ms} ms.",
    "r_forever": "This has run far too long without stopping -- somewhere there is a loop it never gets out of.",
    "r_zero": "That divides by zero.",
    "r_unknown": "Nothing has been put in {name} yet.",
    "r_odd_op": "I do not know what to do with {op}.",
    "r_half": "This does not read as a whole thing: {bit}",
    "r_back": "Back to the run", "back": "Back",
    "r_by_hand": "Press Check the design; if it passes, it can be run here.",
    "h_runnable": "It reads as a program. You can run it now.",
    "h_no_start": "There is no shape to start from.",
    "h_tangled": "The loops in this design cross each other, so it cannot be written out as a program.",
    "h_not_a_program": "The words in these shapes do not read as a program.",
    "r_build_first": "Build a chart from pseudocode and it can be "
                     "run here.",
    "r_copy": "Copy",
    "r_copied": "Copied",
    "r_copy_no": "Copy it by hand",
    "r_save_code": "Save it",
    "r_pseudo_only": "Pick Python, Java, C# or JavaScript to see the code.",
    # ---- where a run went wrong, and what the reading had to paper over
    "r_at": "Line {line}",
    "r_show_line": "Show me the line this came from",
    "r_in_mod": "inside {name}, called from line {line}",
    "r_in_mod_only": "inside {name}",
    "r_mean": "Did you mean {name}?",
    "r_unknown_fn": "There is no module or function called {name}.",
    "r_odd_here": "I did not expect {bit} here.",
    "r_empty_expr": "There is nothing here to work it out from.",
    "r_left_over": "There is {bit} left over at the end of this, with nothing to join it on to.",
    "r_open_quote": "This piece of text is never closed -- a quote mark is missing.",
    "r_open_bracket": "This bracket is opened and never closed.",
    "r_shut_bracket": "This bracket closes one that was never opened.",
    "r_no_idea": "I cannot make sense of this line, so the run stepped over it.",
    "r_stepped_over": "Some lines were stepped over, so what it printed may not be the whole of it.",
    "r_too_deep": "{name} has called itself far too many times -- somewhere it never stops calling.",
    "r_args": "{name} asks for {want} and was given {got}.",
    "r_no_main": "There is no main flow here, so the run started in {name} instead.",
    "w_head": "Worth a look",
    "w_found": "{n} to look at in the pseudocode:",
    "w_open_if": "Line {line}: this If is never closed, so everything below it is inside it. Add an End If where it should stop.",
    "w_open_loop": "Line {line}: this loop is never closed, so everything below it goes round with it. Add an End While where it should stop.",
    "w_open_for": "Line {line}: this For is never closed, so everything below it goes round with it. Add an End For where it should stop.",
    "w_open_select": "Line {line}: this Select is never closed. Add an End Select where it should stop.",
    "w_no_if": "Line {line}: End If, but there is no If open for it to close.",
    "w_no_loop": "Line {line}: this ends a loop, but there is no loop open for it to close.",
    "w_no_select": "Line {line}: End Select, but there is no Select open for it to close.",
    "w_do_no_test": "Line {line}: this Do is never given a test, so it would go round for ever. End it with Until ... or Loop While ...",
    "w_until_alone": "Line {line}: Until, but there is no Do or Repeat above it for it to end.",
    "w_mend_change": "Change {word} to {instead}",
    "w_mend_drop": "Take line {line} out",
    "w_mend_insert": "Put {text} in at line {line}",
    "w_mend_tip": "Double-click to put this right",
    "n_rect": "Box",
    "an_arrow": "Arrow",
    "word_on_it": "Word on it",
    "thickness": "Thickness",
    "color_of_it": "Color",
    "dashed": "Dashed",
    "with_head": "Arrowhead",
    "turn_it_round": "Turn it round",
    "m_type": "Type in it",
    "m_copy": "Make another",
    "c_fill": "Fill color", "c_line": "Border color", "c_words": "Word color",
    "c_clear": "No color of its own",
    "m_turn": "Turn 90°",
    "m_solid": "Solid",
    "m_no_word": "No word",
    "m_fit": "Fit on screen",
    "f_save": "Save this to a file",
    "f_open": "Open a document",
    "f_not_ours": "That is a JSON file, but not a design saved from here.",
    "f_opened": "Opened {name}.",
    "f_empty": "There is nothing written in that one.",
    "n_roundrect": "Rounded box",
    "n_offpage": "Off-page", "n_loop": "Loop limit", "n_parallel": "Side by side",
    "n_text": "Text", "n_actor": "Person", "n_callout": "Speech",
    "n_cube": "Cube", "n_step": "Step", "n_table": "Table",
    "n_stored": "Stored inside", "n_cloud": "Cloud",
    "n_card": "Card",
    "n_note": "Note",
    "n_docs": "Pages",
    "n_manual": "Typed in",
    "n_screen": "Screen",
    "n_arrow": "Arrow",
    "n_io_back": "Parallelogram, other way",
    "n_oval": "Oval",
    "n_io": "Parallelogram",
    "n_diamond": "Diamond",
    "n_hex": "Hexagon",
    "n_sub": "Box with bars",
    "n_trap": "Trapezoid",
    "n_doc": "Document",
    "n_store": "Drum",
    "n_delay": "Wait",
    "n_circle": "Circle",
    "shapes_for": "Shape for each kind",
    "shapes_for_hint": "Which shape gets drawn for each kind of step. What a step means does not change.",
    "size": "Size",
    "width": "Width",
    "height": "Height",
    "turn": "Turn",
    "fit_words": "Fit the words",
    "colors_here": "Colors",
    "odd_shape": "Cannot draw {pair} -- see --help.",
    "mode_code": "From pseudocode",
    "mode_hand": "By hand",
    "add_shape": "Add a shape",
    "hand_hint": "Drag shapes about. Click one, then Connect, then click where the flow goes next.",
    "words_in": "Words in the shape",
    "connect": "Connect",
    "connect_now": "Now click the shape it goes to.",
    "goes_to": "Goes to",
    "nothing_yet": "nothing yet",
    "delete": "Delete",
    "check": "Check the design",
    "checked_good": "This design works: one Start, every shape reached, and every path ends at an End.",
    "problems": "{n} to look at",
    "pick_shape": "Click a shape to give it words, move it, or join it to another.",
    "as_chart": "Chart",
    "untitled": "Untitled",
    "p_no_start": "Nothing starts the flow: every shape has something leading into it.",
    "p_many_starts": "{n} shapes have nothing leading into them. A flowchart starts in one place.",
    "p_start_kind": "The shape everything starts from should be an oval.",
    "p_no_end": "There is no End: no oval that the flow stops at.",
    "p_unreached": "Nothing leads to this shape.",
    "p_dead_end": "Nothing leaves this shape, and it is not an End.",
    "p_decision_out": "A decision needs two ways out, one for each answer. This one has {n}.",
    "p_one_out": "This shape has {n} ways out. Only a decision may have more than one.",
    "p_same_labels": "Both ways out of this decision say the same thing.",
    "p_no_label": "A way out of a decision needs a word on it.",
    "p_trapped": "Once the flow gets here it can never reach an End.",
    "p_empty": "This shape has nothing written in it.",
    "p_overlap": "This shape is on top of another one.",
    "p_alone": "This shape is not joined to anything.",
    "p_line_through": "A line runs straight through this shape. Move one of them over a little.",
    "side_chart": "Chart", "side_colors": "Colors", "hide_panel": "Hide the panel", "show_panel": "Show the panel",
    "theme": "Light or dark", "theme_auto": "Auto", "theme_light": "Light", "theme_dark": "Dark",
    "settings": "Settings", "appearance": "Appearance", "panel_side": "Panel side",
    "side_left": "Left", "side_right": "Right", "full_screen": "Full screen",
    "full_on": "Fill the screen", "full_off": "Leave full screen",
    "no_full": "This browser will not go full screen.",
    "p_ink": "Ink", "p_classic": "Classic", "p_slate": "Slate",
    "p_meadow": "Meadow", "p_sunset": "Sunset", "p_night": "Night",
    # ---- the studio
    "pseudocode": "Pseudocode", "title": "Title", "your_name": "Your name",
    "code_big": "Fill the screen", "code_small": "Back to the panel", "done": "Done",
    "code_esc": "Esc to close", "code_lines": "{n} lines",
    "shape": "Shape",
    "language": "Language", "key_switch": "Key", "tint_switch": "Tints",
    "build": "Build the chart", "drawing": "Drawing…",
    "no_code": "There is no pseudocode to draw yet.",
    "failed": "That did not draw.",
    "not_answering": "The studio is not answering ({err}).",
    "empty_chart": "Paste your pseudocode on the left, then press Build.",
    "shape_auto": "Auto", "shape_square": "Square", "shape_wide": "Wide 16:9",
    "shape_page": "Page", "shape_tall": "Tall",
    # ---- what the script says in the terminal
    "already": "Already there {path}",
    "copied": "Copied {n} files into {dir}",
    "wrote": "Wrote {path}",
    "open_this": "<- open this one: it shows the chart and has the "
                 "download links",
    "style_seed": "Style seed {seed} (pass --seed {seed} to draw this "
                  "one again)",
    "nothing": "No pseudocode given -- nothing to draw.",
    "studio_at": "The flowchart studio is running at {url}",
    "leave_open": "Leave this window open while you use it; press Ctrl+C "
                  "to stop.",
    "stopped": "Studio stopped.",
    "site_done": "That folder is a website. Put it on GitHub Pages (or "
                 "any host that serves files) and it works as it does "
                 "here -- {dir}/README.md has the steps.",
    "starting": "Starting Python in your browser…",
    "ready": "Ready.",
    "boot_failed": "Python could not start in this browser ({err}).",
}

speaks("en", "English", EN)
