"""Every word it says, in French."""
from ..words.lookup import speaks

FR = {
    "start": "Début", "end": "Fin", "ret": "Retour",
    "yes": "Vrai", "no": "Faux", "again": "encore ?",
    "key_oval": "Début / Fin", "key_rect": "Traitement",
    "key_io": "Entrée / Sortie", "key_diamond": "Décision",
    "key_hex": "Boucle", "key_sub": "Appeler un module",
    "palette": "Palette", "shapes": "Formes",
    "selected": "Forme sélectionnée", "rest": "Lignes et papier",
    "fill": "Remplissage", "outline": "Contour", "text": "Texte",
    "paper": "Papier", "grid": "Grille", "show_grid": "Afficher la grille",
    "lines": "Lignes et flèches", "reset": "Rétablir toutes les couleurs",
    "download": "Télécharger", "dl_size": "Taille",
    "files": "Fichiers", "import_head": "Importer",
    "dl_svg": "Télécharger le SVG", "dl_png": "Télécharger le PNG",
    "print_it": "Imprimer le schéma",
    "print_head": "Imprimer",
    "print_go": "Imprimer…",
    "print_paper": "Papier",
    "print_wide": "À l’italienne",
    "print_fit": "Tenir sur une page",
    "print_note": "L’impression est sobre : pas de couleurs, seulement des traits et des mots. Quelle imprimante et combien de copies, votre navigateur le demande lui-même — une page n’en a pas le droit.",
    "panel": "Panneau", "panel_tip": "Afficher ou masquer le panneau",
    "png_tip": "Taille du PNG",
    "fit": "Ajuster", "actual": "Réel", "zoom_in": "Agrandir",
    "slide_left": "Gauche", "slide_right": "Droite", "slide_up": "Haut", "slide_down": "Bas",
    "hold_locked": "Fixé", "hold_loose": "Libre",
    "lock_tip": "Garder le schéma en place, en défilant dans la zone",
    "loose_tip": "Déplacez le schéma où vous voulez ; un coin reste toujours visible",
    "zoom_out": "Réduire", "pixels": "pixels",
    "dl_scale": "Fois la taille dessinée",
    "dl_frame": "Ajusté dans une image",
    "png_over": "plus que ce navigateur ne peut dessiner",
    "click_shape": "Cliquez sur une forme de l'organigramme pour ne "
                   "colorer que celle-là.",
    "palette_hint": "Une palette change toutes les formes d'un coup. Ce "
                    "que vous changez ensuite à la main est conservé.",
    "shapes_hint": "Remplissage et contour, pour toutes les formes de ce type.",
    "apply_all": "Appliquer aux {n} formes : {what}", "clear": "Effacer",
    "rendering": "Rendu…",
    "png_big": "Le navigateur n'a pas pu créer un PNG aussi grand. "
               "Essayez une taille plus petite, ou enregistrez le SVG.",
    "png_fail": "Le navigateur n'a pas pu dessiner le PNG. Le "
                "téléchargement du SVG fonctionne toujours.",
    "png_capped": "{want}× dépasse ce qu'un canvas de navigateur "
                  "accepte ; le PNG est donc enregistré à {got}× "
                  "({w} × {h} pixels).",
    "flowchart": "Organigramme",
    "r_head": "Exécuter",
    "r_run": "Lancer",
    "r_stop": "Arrêter",
    "r_code": "En code",
    "r_pseudo": "Pseudocode",
    "r_slowly": "Pas à pas",
    "r_follow": "Suivre le pas",
    "r_follow_tip": "Pendant les pas, le schéma se déplace et zoome sur la forme en cours, et le pseudocode défile jusqu'à sa ligne",
    "r_enter": "Entrer",
    "r_hint": "Exécute le programme dont vient l'organigramme : il demande ce qu'il demande à une personne, affiche ce qu'il affiche, et éclaire la forme où il en est. Choisissez un langage pour voir le même programme écrit dedans.",
    "r_started": "Exécution...",
    "r_done": "Terminé.",
    "r_nothing": "Il n'y a encore rien à exécuter.",
    "r_steps": "{n} étapes, {ms} ms.",
    "r_forever": "Cela tourne depuis bien trop longtemps : quelque part il y a une boucle dont il ne sort jamais.",
    "r_zero": "Cela divise par zéro.",
    "r_unknown": "Rien n'a encore été mis dans {name}.",
    "r_odd_op": "Je ne sais pas quoi faire de {op}.",
    "r_half": "Cela ne se lit pas comme un tout : {bit}",
    "r_back": "Retour à l’exécution", "back": "Retour",
    "r_by_hand": "Appuyez sur Vérifier le schéma ; s’il passe, il peut être exécuté ici.",
    "h_runnable": "Cela se lit comme un programme. Vous pouvez l’exécuter.",
    "h_no_start": "Il n’y a aucune forme par laquelle commencer.",
    "h_tangled": "Les boucles de ce schéma se croisent, il ne peut donc pas être écrit comme un programme.",
    "h_not_a_program": "Les mots de ces formes ne se lisent pas comme un programme.",
    "r_build_first": "Construisez un organigramme à partir de "
                     "pseudocode et il pourra être exécuté ici.",
    "r_copy": "Copier",
    "r_copied": "Copié",
    "r_copy_no": "À copier à la main",
    "r_save_code": "Enregistrer",
    "r_pseudo_only": "Choisissez Python, Java, C# ou JavaScript pour voir le code.",
    # ---- où l'exécution a échoué, et ce que la lecture a dû rattraper
    "r_at": "Ligne {line}",
    "r_show_line": "Montre-moi la ligne d'où cela vient",
    "r_in_mod": "dans {name}, appelé depuis la ligne {line}",
    "r_in_mod_only": "dans {name}",
    "r_mean": "Vouliez-vous dire {name} ?",
    "r_unknown_fn": "Il n'existe aucun module ni aucune fonction nommée {name}.",
    "r_odd_here": "Je ne m'attendais pas à {bit} ici.",
    "r_empty_expr": "Il n'y a rien ici pour le calculer.",
    "r_left_over": "Il reste {bit} à la fin, sans rien à quoi le rattacher.",
    "r_open_quote": "Ce texte n'est jamais refermé : il manque un guillemet.",
    "r_open_bracket": "Cette parenthèse est ouverte et jamais refermée.",
    "r_shut_bracket": "Cette parenthèse en referme une qui n'a jamais été ouverte.",
    "r_no_idea": "Je n'arrive pas à lire cette ligne, l'exécution l'a donc enjambée.",
    "r_stepped_over": "Des lignes ont été enjambées : ce qui a été affiché n'est peut-être pas tout.",
    "r_too_deep": "{name} s'est appelé bien trop de fois : quelque part, il ne cesse jamais de s'appeler.",
    "r_args": "{name} demande {want} et en a reçu {got}.",
    "r_no_main": "Il n'y a pas de flux principal ici : l'exécution a donc commencé dans {name}.",
    "w_head": "À regarder",
    "w_found": "{n} à regarder dans le pseudocode :",
    "w_open_if": "Ligne {line} : ce If n'est jamais refermé, donc tout ce qui suit est dedans. Ajoutez un End If là où il doit s'arrêter.",
    "w_open_loop": "Ligne {line} : cette boucle n'est jamais refermée, donc tout ce qui suit tourne avec elle. Ajoutez un End While là où elle doit s'arrêter.",
    "w_open_for": "Ligne {line} : ce For n'est jamais fermé, donc tout ce qui suit tourne avec lui. Ajoutez un End For là où il doit s'arrêter.",
    "w_open_select": "Ligne {line} : ce Select n'est jamais refermé. Ajoutez un End Select là où il doit s'arrêter.",
    "w_no_if": "Ligne {line} : End If, mais aucun If n'est ouvert à refermer.",
    "w_no_loop": "Ligne {line} : ceci referme une boucle, mais aucune boucle n'est ouverte.",
    "w_no_select": "Ligne {line} : End Select, mais aucun Select n'est ouvert à refermer.",
    "w_do_no_test": "Ligne {line} : ce Do ne reçoit aucun test, il tournerait donc sans fin. Terminez-le par Until ... ou Loop While ...",
    "w_until_alone": "Ligne {line} : Until, mais il n'y a ni Do ni Repeat au-dessus à refermer.",
    "w_mend_change": "Remplacer {word} par {instead}",
    "w_mend_drop": "Retirer la ligne {line}",
    "w_mend_insert": "Mettre {text} à la ligne {line}",
    "w_mend_tip": "Double-cliquez pour corriger",
    "n_rect": "Rectangle",
    "an_arrow": "Flèche",
    "word_on_it": "Mot dessus",
    "thickness": "Épaisseur",
    "color_of_it": "Couleur",
    "dashed": "Pointillés",
    "with_head": "Pointe",
    "turn_it_round": "Inverser",
    "m_type": "Écrire dedans",
    "m_copy": "Dupliquer",
    "c_fill": "Couleur de fond", "c_line": "Couleur du bord", "c_words": "Couleur du texte",
    "c_clear": "Aucune couleur propre",
    "m_turn": "Tourner de 90°",
    "m_solid": "Trait plein",
    "m_no_word": "Aucun mot",
    "m_fit": "Ajuster à l'écran",
    "f_save": "Enregistrer dans un fichier",
    "f_open": "Ouvrir un document",
    "f_not_ours": "C’est un fichier JSON, mais pas un schéma enregistré ici.",
    "f_opened": "{name} est ouvert.",
    "f_empty": "Il n’y a rien d’écrit dedans.",
    "n_roundrect": "Boîte arrondie",
    "n_offpage": "Hors page", "n_loop": "Limite de boucle", "n_parallel": "En parallèle",
    "n_text": "Texte", "n_actor": "Personne", "n_callout": "Bulle",
    "n_cube": "Cube", "n_step": "Étape", "n_table": "Tableau",
    "n_stored": "Stocké à l’intérieur", "n_cloud": "Nuage",
    "n_card": "Carte",
    "n_note": "Note",
    "n_docs": "Pages",
    "n_manual": "Saisie manuelle",
    "n_screen": "Écran",
    "n_arrow": "Flèche",
    "n_io_back": "Parallélogramme inversé",
    "n_oval": "Ovale",
    "n_io": "Parallélogramme",
    "n_diamond": "Losange",
    "n_hex": "Hexagone",
    "n_sub": "Boîte à barres",
    "n_trap": "Trapèze",
    "n_doc": "Document",
    "n_store": "Tambour",
    "n_delay": "Attente",
    "n_circle": "Cercle",
    "shapes_for": "Forme de chaque type",
    "shapes_for_hint": "Quelle forme est dessinée pour chaque type d'étape. Ce que l'étape veut dire ne change pas.",
    "size": "Taille",
    "width": "Largeur",
    "height": "Hauteur",
    "turn": "Tourner",
    "fit_words": "Ajuster au texte",
    "colors_here": "Couleurs",
    "odd_shape": "Impossible de dessiner {pair} ; voir --help.",
    "mode_code": "À partir du pseudocode",
    "mode_hand": "À la main",
    "add_shape": "Ajouter une forme",
    "hand_hint": "Déplacez les formes. Cliquez sur l'une, puis sur Relier, puis sur la forme où va la suite.",
    "words_in": "Texte de la forme",
    "connect": "Relier",
    "connect_now": "Cliquez maintenant sur la forme où cela va.",
    "goes_to": "Va vers",
    "nothing_yet": "rien encore",
    "delete": "Supprimer",
    "check": "Vérifier le schéma",
    "checked_good": "Le schéma tient : un seul Début, toutes les formes atteintes, et tous les chemins finissent sur une Fin.",
    "problems": "{n} choses à revoir",
    "pick_shape": "Cliquez sur une forme pour y écrire, la déplacer ou la relier à une autre.",
    "as_chart": "Organigramme",
    "untitled": "Sans titre",
    "p_no_start": "Rien ne commence le flux : chaque forme a quelque chose qui y mène.",
    "p_many_starts": "{n} formes n'ont rien qui y mène. Un organigramme commence à un seul endroit.",
    "p_start_kind": "La forme par laquelle tout commence devrait être un ovale.",
    "p_no_end": "Il n'y a pas de Fin : aucun ovale où le flux s'arrête.",
    "p_unreached": "Rien ne mène à cette forme.",
    "p_dead_end": "Rien ne sort de cette forme, et ce n'est pas une Fin.",
    "p_decision_out": "Une décision a deux sorties, une par réponse. Celle-ci en a {n}.",
    "p_one_out": "Cette forme a {n} sorties. Seule une décision peut en avoir plus d'une.",
    "p_same_labels": "Les deux sorties de cette décision disent la même chose.",
    "p_no_label": "Une sortie de décision a besoin d'un mot.",
    "p_trapped": "Une fois arrivé ici, le flux ne peut plus atteindre de Fin.",
    "p_empty": "Rien n'est écrit dans cette forme.",
    "p_overlap": "Cette forme est posée sur une autre.",
    "p_alone": "Cette forme n'est reliée à rien.",
    "p_line_through": "Une ligne traverse cette forme. Déplacez un peu l'une ou l'autre.",
    "side_chart": "Schéma", "side_colors": "Couleurs", "hide_panel": "Masquer le panneau", "show_panel": "Afficher le panneau",
    "theme": "Clair ou sombre", "theme_auto": "Auto", "theme_light": "Clair", "theme_dark": "Sombre",
    "settings": "Réglages", "appearance": "Apparence", "panel_side": "Côté du panneau",
    "side_left": "Gauche", "side_right": "Droite", "full_screen": "Plein écran",
    "full_on": "Remplir l’écran", "full_off": "Quitter le plein écran",
    "no_full": "Ce navigateur ne passe pas en plein écran.",
    "p_ink": "Encre", "p_classic": "Classique", "p_slate": "Ardoise",
    "p_meadow": "Prairie", "p_sunset": "Couchant", "p_night": "Nuit",
    "pseudocode": "Pseudocode", "title": "Titre", "your_name": "Votre nom",
    "code_big": "Remplir l’écran", "code_small": "Revenir au panneau", "done": "Terminé",
    "code_esc": "Échap pour fermer", "code_lines": "{n} lignes",
    "shape": "Forme",
    "language": "Langue", "key_switch": "Légende", "tint_switch": "Teintes",
    "build": "Dessiner l'organigramme", "drawing": "Dessin…",
    "no_code": "Il n'y a pas encore de pseudocode à dessiner.",
    "failed": "Le dessin a échoué.",
    "not_answering": "Le studio ne répond pas ({err}).",
    "empty_chart": "Collez votre pseudocode à gauche, puis cliquez sur "
                   "Dessiner.",
    "shape_auto": "Auto", "shape_square": "Carré", "shape_wide": "Large 16:9",
    "shape_page": "Page", "shape_tall": "Haut",
    "already": "Déjà là {path}",
    "copied": "{n} fichiers copiés dans {dir}",
    "wrote": "Écrit {path}",
    "open_this": "<- ouvrez celui-ci : il montre l'organigramme et porte "
                 "les liens de téléchargement",
    "style_seed": "Graine de style {seed} (passez --seed {seed} pour le "
                  "redessiner à l'identique)",
    "nothing": "Aucun pseudocode donné -- rien à dessiner.",
    "studio_at": "Le studio d'organigrammes tourne sur {url}",
    "leave_open": "Laissez cette fenêtre ouverte pendant que vous vous en "
                  "servez ; Ctrl+C pour l'arrêter.",
    "stopped": "Studio arrêté.",
    "site_done": "Ce dossier est un site web. Mettez-le sur GitHub Pages "
                 "(ou tout hébergeur de fichiers) et il marchera comme "
                 "ici ; les étapes sont dans {dir}/README.md.",
    "starting": "Démarrage de Python dans le navigateur…",
    "ready": "Prêt.",
    "boot_failed": "Python n'a pas pu démarrer dans ce navigateur ({err}).",
}

speaks("fr", "Français", FR)
